name       : krita
version    : 4.1.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/krita/4.1.0/krita-4.1.0.tar.gz : 78792df8165b986b806dcf9960a2679f683f2263e06f3ad5a24b0f78d8f27ed5
license    :
    - GPL-3.0-only
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application
description: |
    Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(python3)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - giflib-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - python3-qt5
    - python3-sip-devel
    - vc
rundeps    :
    - breeze
    - ffmpeg
    - python3-qt5
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
           -DPACKAGERS_BUILD=ON \
           -DQT_NO_DEBUG=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    rm -rf $installdir/usr/share/applications/krita*.desktop
