name       : krita
version    : 3.0.1.1
release    : 7
source     :
    - http://download.kde.org/stable/krita/3.0.1.1/krita-3.0.1.1.tar.gz : b36ce546fd5a469485496171add94c0deda3c26bdb7a688b7d593f5155baa86c
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application.
description: |
    Free and open source digital painting application.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - vc
rundeps    :
    - breeze
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DCMAKE_CXX_FLAGS="%CXXFLAGS% -DKDE_NO_DEBUG_OUTPUT" \
           -DPACKAGERS_BUILD=ON \
           -DQT_NO_DEBUG=1 ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    rm $installdir/usr/share/color-schemes/Breeze{Dark,HighContrast}.colors
