name       : krita
version    : 4.4.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/krita/4.4.2/krita-4.4.2.tar.xz : 1ee503afc86178e1abbae63e8334e26116a6779aa9ef202656a1c35b76932e88
homepage   : https://krita.org
license    : GPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application
description: |
    Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libheif)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(poppler-qt5)
    - pkgconfig(python3)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - giflib-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - python3-qt5
    - python3-sip-devel
    - quazip-devel
    - vc
rundeps    :
    - breeze
    - ffmpeg
    - python3-qt5
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DPACKAGERS_BUILD=ON \
           -DQT_NO_DEBUG=ON ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    %qml_cache

    rm -rf $installdir/usr/share/applications/krita*.desktop
