name       : krita
version    : 3.0.1
release    : 3
source     :
    - https://github.com/KDE/krita/archive/v3.0.1.tar.gz : eac5e2f316b06ecd3ef50e0477a376b1811a57a73c1a4b736a988f59491b0d80
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application.
description: |
    Free and open source digital painting application.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - vc
rundeps    :
    - breeze
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DPACKAGERS_BUILD=ON \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    rm $installdir/usr/share/color-schemes/Breeze{Dark,HighContrast}.colors
