name       : krita
version    : 3.0
release    : 1
source     :
    - https://github.com/KDE/krita/archive/v3.0.tar.gz : 4cea85623b709d6d32084c98a0fd76b97ad96d11be9808fca9fcaad2839a9c5a
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application.
description: |
    Free and open source digital painting application.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - vc
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DPACKAGERS_BUILD=ON \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
