name       : krita
version    : 4.1.7
release    : 43
source     :
    - https://cdn.download.kde.org/stable/krita/4.1.7/krita-4.1.7.tar.gz : c16ec0dd23cdf20e9dd4d34ebabcf5bdb06a825bd6fe2c7196d6777279bdabd0
license    :
    - GPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application
description: |
    Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libheif)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(poppler-qt5)
    - pkgconfig(python3)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - giflib-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - python3-qt5
    - python3-sip-devel
    - vc
rundeps    :
    - breeze
    - ffmpeg
    - python3-qt5
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
           -DPACKAGERS_BUILD=ON \
           -DQT_NO_DEBUG=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    rm -rf $installdir/usr/share/applications/krita*.desktop
