name       : krita
version    : 5.0.5
release    : 80
source     :
    - https://cdn.download.kde.org/stable/krita/5.0.5/krita-5.0.5.tar.xz : 78d53659266cf8c50cfeabb357d597ad4fc1afc8dbd0553a67d63623bd6bc671
    - https://github.com/amyspark/gmic/releases/download/v3.0.2.1/gmic-3.0.2.1-patched.tar.xz : 3a45ed88e690db458a973239e5a6b5abbf963315d2fd63af8d155b150fffc428
homepage   : https://krita.org
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Free and open source digital painting application
description: |
    Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.
patterns   : /*
networking : yes
builddeps  :
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gsl)
    - pkgconfig(kseexpr)
    - pkgconfig(libheif)
    - pkgconfig(libmypaint)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(poppler-qt5)
    - pkgconfig(python3)
    - pkgconfig(quazip)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - giflib-devel
    - gmic-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - python-sip
    - python3-qt5
    - subversion
    - vc
rundeps    :
    - breeze
    - ffmpeg
    - python3-qt5
setup      : |
    tar -xf $sources/gmic-3.0.2.1-patched.tar.xz -C .

    %cmake_ninja -DBUILD_TESTING=OFF \
                 -DENABLE_UPDATERS=OFF \
                 -DFETCH_TRANSLATIONS=ON \
                 -DBUILD_KRITA_QT_DESIGNER_PLUGINS=ON \
                 -DKDE_INSTALL_CONFDIR=/usr/share/defaults/krita
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/applications/krita*.desktop

    pushd gmic-3.0.2.1-patched/gmic-qt
    %cmake_ninja -DCMAKE_PREFIX_PATH=$installdir/usr \
                 -DENABLE_SYSTEM_GMIC=ON \
                 -DGMIC_QT_HOST=krita-plugin
    %ninja_build
    %ninja_install
    popd

    %qml_cache
