name       : krita
version    : 3.2.1
release    : 17
source     :
    - https://download.kde.org/stable/krita/3.2.1/krita-3.2.1.tar.gz : ef06cee677d75861edca0e1f825bca42ff59b7200aeb827e16f8d1fb5ef14e39
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application.
description: |
    Free and open source digital painting application.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - vc
rundeps    :
    - breeze
    - ffmpeg
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DCMAKE_CXX_FLAGS="%CXXFLAGS% -DKDE_NO_DEBUG_OUTPUT" \
           -DPACKAGERS_BUILD=ON \
           -DQT_NO_DEBUG=1 ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    rm -rf $installdir/usr/share/applications/krita*.desktop
