name       : krita
version    : 3.0.1
release    : 4
source     :
    - http://files.kde.org/krita/3/source/krita-3.0.1.tar.gz : 3c820ec30c3f4c93a33e2982571017eac8f8af2a734a6a1474ef11e1db26d006
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application.
description: |
    Free and open source digital painting application.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - vc
rundeps    :
    - breeze
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DPACKAGERS_BUILD=ON \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    rm $installdir/usr/share/color-schemes/Breeze{Dark,HighContrast}.colors
