name       : krita
version    : 4.0.0
release    : 30
source     :
    - https://download.kde.org/stable/krita/4.0.0/krita-4.0.0.tar.gz : 5ff1925361c65e5a8ca6949035ef3d1291488b63f0f473dbf62bf70a525d0336
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.graphics
libsplit   : no
summary    : Free and open source digital painting application.
description: |
    Free and open source digital painting application.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(eigen3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenColorIO)
    - pkgconfig(python3)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - extra-cmake-modules
    - giflib-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
    - python3-qt5
    - python3-sip-devel
    - vc
rundeps    :
    - breeze
    - ffmpeg
    - python3-qt5
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_TESTING=OFF \
           -DCMAKE_CXX_FLAGS="%CXXFLAGS% -DKDE_NO_DEBUG_OUTPUT" \
           -DPACKAGERS_BUILD=ON \
           -DQT_NO_DEBUG=ON \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    rm -rf $installdir/usr/share/applications/krita*.desktop

    # precompile QML files
    cd $installdir; qml_cache
